# Generated by Django 6.0.5 on 2026-06-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyGym', '0002_nutrition_schedule_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='category',
            field=models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('legs', 'Legs'), ('abs', 'Abs')], default='chest', max_length=20),
        ),
        migrations.AddField(
            model_name='workout',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste an animated GIF URL here', null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.TextField(help_text='Enter variation details, sets, and reps.'),
        ),
    ]
