# Generated by Django 6.0.5 on 2026-06-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyGym', '0003_workout_category_workout_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='experience_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='fitness_goal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
