# Generated by Django 6.0.5 on 2026-06-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyGym', '0006_bodystat'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
