# Generated by Django 6.0.5 on 2026-06-04 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyGym', '0008_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('muscle_group', models.CharField(default='Custom', max_length=50)),
                ('exercises', models.TextField(blank=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('exercise_count', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('color', models.CharField(default='#a0aec0', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
