# Generated by Django 6.0.5 on 2026-06-04 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyGym', '0009_workoutsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='color',
            field=models.CharField(choices=[('#e63329', 'Red'), ('#48bb78', 'Green'), ('#4299e1', 'Blue'), ('#ed8936', 'Orange'), ('#9f7aea', 'Purple')], default='#e63329', max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='schedule',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='exercise_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='exercises',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='schedule',
            name='muscle_group',
            field=models.CharField(default='Full Body', max_length=50),
        ),
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schedule',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='activity',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='activity',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='day',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
